[package]
name = "qt_rust_app"
version = "0.1.0"
edition = "2021"

[dependencies]
qmetaobject = "0.2"
libloading = "0.8"
cstr = "0.2"
quick-xml = { version = "0.37.4", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
